a=input()
print("My name is ",a)
a1=input("Enter your name:")
print(a1)
x = input("Enter first number ")
y = input("Enter second number ")
print(x+y)
print(int(x)+int(y))

a=input("Enter a number : ")
b=input("Enter a number : ")

print("The value of", a, "+", b ,"is: ",int(a) + int(b))
print("The value of", a, "+", b ,"is: ", a + b)
# print("The value of", a, "-", b ,"is: ", a - b) error
print("The value of", a, "-", b ,"is: ", int(a) - int(b))
#print("The value of", a, "*", b ,"is: ", a * b)
print("The value of", a, "*", b ,"is: ", int(a) * int(b))
#print("The value of", a, "/", b ,"is: ", a / b)
print("The value of", a, "/", b ,"is: ", int(a) / int(b))
#print("The value of", a, "//", b ,"is: ", a//b)
print("The value of", a, "//", b ,"is: ", int(a) // int(b))
#print("The value of", a, "%", b ,"is: ", a % b)
print("The value of", a, "%", b ,"is: ", int(a) % int(b))